services:
  - type: web
    name: econoch
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 